title: Krati Paw Portfolio
logo: "/images/logo.png?raw=true"
description: > 
  Software Engineer with 5+ years experience building applications and services in the ITOps and infrastructure monitoring space using Java, C++. 
  <br><br>
  Adept in Java, Problem Solving (Top 1% coder on InterviewBit), OOPS paradigm, Git, Scala.
  <br><br>
  <a href="https://www.linkedin.com/in/kratipaw/">LinkedIn</a><br> 
  <a href="https://www.github.com/kratipaw/">GitHub</a>

theme: jekyll-theme-dinky
