title: Krati Paw Portfolio
description: > 
  Software Engineer with 5+ years experience building applications and services in the ITOps and infrastructure monitoring space using Java, C++. 
  <br><br>
  Adept in Java, Problem Solving (DS & Algo, Top 1% coder in InterviewBit), OOPS, REST, GraphQL, Spring Boot, MySQL, MongoDB, Swagger, OAuth, Jenkins, Git, Scala.

theme: jekyll-theme-architect
google_analytics: UA-146799261-1
